services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: krvvko-me:latest
    container_name: krvvko-me
    restart: unless-stopped
    ports:
      - "3020:3020"
    environment:
      NODE_ENV: production
      PORT: 3020
      HOSTNAME: 0.0.0.0
